---
title: "ob work"
author: "Adrian"
date: "18 september 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(tidyverse)
```

Equinor og Hydro sin data
```{r}
library(readr)
eqnr <- read_csv("https://www.netfonds.no/quotes/paperhistory.php?paper=EQNR.OSE&csv_format=csv", 
    col_types = cols(quote_date = col_date(format = "%Y%m%d")))
View(eqnr)

library(readr)
Hydro <- read_delim("https://www.netfonds.no/quotes/paperhistory.php?paper=NHY.OSE&csv_format=sdv", 
    ";", escape_double = FALSE, col_types = cols(quote_date = col_date(format = "%Y%m%d")), 
    trim_ws = TRUE)
View(Hydro)
```

Så bruker man "merge" for å slå sammen datene til Hydro og Equinor. 

```{r, fig.height= 5, fig.width=10}
merge_data <- merge(eqnr, Hydro, by= "quote_date",all.x=T)
View(merge_data)

ggplot2::ggplot(data=merge_data, aes(x=quote_date))+
  geom_line(aes(y = close.x , color = "#00AFBB"))+
              geom_line(aes(y= close.y,color = "#FC4E07"))+
  xlab("date")+
  ylab("value")
```
Grafen viser til norsk hydro og equinor sine aksje kurser etter at aksjemarkedet har stengt. der hvor hydro(#FC4E07) er mye lavere enn det Equinor(#00AFBB).
